import {onSchedule} from "firebase-functions/v2/scheduler";
import {logger} from "firebase-functions";
import admin from "firebase-admin";
import nodemailer from "nodemailer";

if (!admin.apps || admin.apps.length === 0) {
  admin.initializeApp();
}

const db = admin.firestore();

/**
 * Compute next run from schedule + current "now"
 */
function computeNextRun(schedule, now) {
  const next = new Date(now.getTime());
  const {frequency, dayOfWeek, dayOfMonth, time} = schedule;
  const [hh, mm] = (time || "09:00").split(":").map((v) => parseInt(v || "0", 10));

  // NOTE: For simplicity we ignore timezone offset and just use server time
  next.setSeconds(0, 0);

  if (frequency === "daily") {
    next.setHours(hh, mm, 0, 0);
    if (next <= now) {
      next.setDate(next.getDate() + 1);
    }
  } else if (frequency === "weekly") {
    const target = (typeof dayOfWeek === "number" ? dayOfWeek : 1) % 7;
    const curDow = next.getDay();
    let diff = target - curDow;
    if (diff <= 0) diff += 7;
    next.setDate(next.getDate() + diff);
    next.setHours(hh, mm, 0, 0);
  } else if (frequency === "monthly") {
    const dom = Math.min(Math.max(dayOfMonth || 1, 1), 28);
    next.setDate(dom);
    next.setHours(hh, mm, 0, 0);
    if (next <= now) {
      next.setMonth(next.getMonth() + 1);
      next.setDate(dom);
    }
  } else {
    // custom / fallback: run again tomorrow
    next.setDate(next.getDate() + 1);
    next.setHours(hh, mm, 0, 0);
  }

  return admin.firestore.Timestamp.fromDate(next);
}

async function getSettings() {
  const snap = await db.collection("settings").doc("general").get();
  if (!snap.exists) return null;
  return snap.data();
}

function buildSmtpTransport(settings) {
  const smtp = settings?.email?.smtp;
  if (!smtp || !smtp.host || !smtp.port || !smtp.username || !smtp.fromEmail) {
    logger.warn("SMTP settings incomplete; scheduled report emails will be skipped.");
    return null;
  }

  const transporter = nodemailer.createTransport({
    host: smtp.host,
    port: parseInt(String(smtp.port), 10),
    secure: smtp.encryption === "ssl",
    auth: {
      user: smtp.username,
      pass: smtp.password || "",
    },
    tls: {rejectUnauthorized: false},
  });

  return {transporter, smtp};
}

function buildReportHtml(reportDoc, templateDoc) {
  const report = reportDoc.data();
  const tpl = templateDoc.data();
  const period = report?.period;
  const start = period?.start?.toDate ? period.start.toDate() : null;
  const end = period?.end?.toDate ? period.end.toDate() : null;

  const lines = [];
  lines.push(`<h1 style="font-family:system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;">${tpl?.name || "Scheduled Report"}</h1>`);
  lines.push(`<p>Type: <strong>${tpl?.type || "custom"}</strong></p>`);
  if (start && end) {
    lines.push(`<p>Period: <strong>${start.toISOString().slice(0, 10)}</strong> to <strong>${end.toISOString().slice(0, 10)}</strong></p>`);
  }
  lines.push("<hr />");

  // Very simple auto-summary for a few known metrics if present
  if (report?.revenue) {
    lines.push("<h2>Revenue</h2>");
    lines.push("<ul>");
    lines.push(`<li>Total: <strong>${report.revenue.total}</strong></li>`);
    if (typeof report.revenue.productSales === "number") {
      lines.push(`<li>Product Sales: ${report.revenue.productSales}</li>`);
    }
    if (typeof report.revenue.shipping === "number") {
      lines.push(`<li>Shipping: ${report.revenue.shipping}</li>`);
    }
    if (typeof report.revenue.taxes === "number") {
      lines.push(`<li>Taxes: ${report.revenue.taxes}</li>`);
    }
    lines.push("</ul>");
  }

  if (report?.profit) {
    lines.push("<h2>Profit</h2>");
    lines.push("<ul>");
    lines.push(`<li>Gross: ${report.profit.gross}</li>`);
    lines.push(`<li>Net: ${report.profit.net}</li>`);
    lines.push(`<li>Margin: ${report.profit.margin?.toFixed?.(1) ?? report.profit.margin}%</li>`);
    lines.push("</ul>");
  }

  if (report?.orders) {
    lines.push("<h2>Orders</h2>");
    lines.push("<ul>");
    lines.push(`<li>Total: ${report.orders.total}</li>`);
    lines.push(`<li>Completed: ${report.orders.completed}</li>`);
    lines.push(`<li>Cancelled: ${report.orders.cancelled}</li>`);
    lines.push(`<li>Refunded: ${report.orders.refunded}</li>`);
    lines.push("</ul>");
  }

  lines.push("<p style=\"margin-top:24px;font-size:12px;color:#6b7280;\">");
  lines.push("This is an automated email generated by Pardah analytics scheduled reports.");
  lines.push("</p>");

  return lines.join("\n");
}

async function generateReportForTemplate(templateDoc, schedule) {
  const tpl = templateDoc.data();
  if (!tpl) return null;

  // For now, we only generate a simple financial/sales style summary.
  // We compute a period based on template.filters.dateRange if present,
  // otherwise use the last N days based on schedule frequency.
  let start;
  let end;

  const now = new Date();
  if (tpl.filters?.dateRange?.start?.toDate && tpl.filters?.dateRange?.end?.toDate) {
    start = tpl.filters.dateRange.start.toDate();
    end = tpl.filters.dateRange.end.toDate();
  } else {
    end = now;
    const d = new Date(now.getTime());
    if (schedule.frequency === "daily") {
      d.setDate(d.getDate() - 1);
    } else if (schedule.frequency === "weekly") {
      d.setDate(d.getDate() - 7);
    } else if (schedule.frequency === "monthly") {
      d.setMonth(d.getMonth() - 1);
    } else {
      d.setDate(d.getDate() - 7);
    }
    start = d;
  }

  // Build a very small "report" object mirroring part of FinancialReport
  // Aggregate over orders for that period.
  const ordersSnap = await db.collection("orders")
      .where("createdAt", ">=", admin.firestore.Timestamp.fromDate(start))
      .where("createdAt", "<=", admin.firestore.Timestamp.fromDate(end))
      .get();

  let totalRevenue = 0;
  let shippingRevenue = 0;
  let taxesCollected = 0;
  let completed = 0;
  let cancelled = 0;
  let refunded = 0;

  ordersSnap.forEach((doc) => {
    const o = doc.data();
    const total = o.totalAmount || 0;
    const shipping = o.shippingCost || 0;
    const tax = o.tax || 0;
    const status = o.status || "pending";

    totalRevenue += total;
    shippingRevenue += shipping;
    taxesCollected += tax;

    if (status === "delivered" || status === "completed") completed++;
    if (status === "cancelled") cancelled++;
    if (status === "refunded") refunded++;
  });

  const productSales = totalRevenue - shippingRevenue;

  const report = {
    period: {
      start: admin.firestore.Timestamp.fromDate(start),
      end: admin.firestore.Timestamp.fromDate(end),
    },
    revenue: {
      total: totalRevenue,
      productSales,
      shipping: shippingRevenue,
      taxes: taxesCollected,
    },
    profit: {
      gross: productSales,
      net: productSales, // we skip detailed costs here
      margin: totalRevenue > 0 ? (productSales / totalRevenue) * 100 : 0,
    },
    orders: {
      total: ordersSnap.size,
      completed,
      cancelled,
      refunded,
    },
  };

  return report;
}

export const scheduledReportsRunner = onSchedule(
    {
      // Run every hour
      schedule: "0 * * * *",
      timeZone: "UTC",
      retryCount: 0,
    },
    async () => {
      logger.info("Running scheduledReportsRunner cron...");
      const now = new Date();
      const settings = await getSettings();
      const smtpInfo = buildSmtpTransport(settings);

      if (!smtpInfo) {
        logger.warn("No valid SMTP config; skipping emails.");
      }

      const snap = await db.collection("scheduled_reports")
          .where("enabled", "==", true)
          .get();

      if (snap.empty) {
        logger.info("No scheduled_reports found.");
        return;
      }

      for (const docSnap of snap.docs) {
        try {
          const reportData = docSnap.data();
          const nextRun = reportData.nextRun?.toDate?.();

          if (!nextRun || nextRun > now) {
            continue;
          }

          const templateId = reportData.templateId;
          const recipients = reportData.recipients || [];
          if (!templateId || !Array.isArray(recipients) || recipients.length === 0) {
            logger.warn(`Skipping scheduled_report ${docSnap.id} due to missing templateId/recipients`);
            continue;
          }

          const templateDoc = await db.collection("custom_report_templates").doc(templateId).get();
          if (!templateDoc.exists) {
            logger.warn(`Template ${templateId} not found for scheduled_report ${docSnap.id}`);
            continue;
          }

          const schedule = reportData.schedule || {
            frequency: "weekly",
            time: "09:00",
            timezone: "UTC",
          };

          const generatedReport = await generateReportForTemplate(templateDoc, schedule);
          if (!generatedReport) {
            logger.warn(`No report generated for template ${templateId}`);
            continue;
          }

          const html = buildReportHtml(
              {data: () => generatedReport},
              {data: () => templateDoc.data()},
          );

          if (smtpInfo) {
            const subject = `[Pardah] ${templateDoc.data().name || "Scheduled Report"}`;
            await smtpInfo.transporter.sendMail({
              from: `"${smtpInfo.smtp.fromName || "Pardah Reports"}" <${smtpInfo.smtp.fromEmail}>`,
              to: recipients.join(", "),
              subject,
              html,
            });
            logger.info(`Sent scheduled report ${docSnap.id} to ${recipients.join(",")}`);
          }

          // Update lastRun and nextRun
          const nextRunTs = computeNextRun(schedule, now);
          await docSnap.ref.update({
            lastRun: admin.firestore.Timestamp.fromDate(now),
            nextRun: nextRunTs,
          });
        } catch {
          logger.error(`Error processing scheduled_report ${docSnap.id}`, err);
        }
      }
    },
);


